version: '3.5'

services:
  iroha-node0:
    image: hyperledger/iroha:1.1.1
    container_name: iroha-node0
    expose:
      - 10001
    ports:
      - 50051:50051
    environment:
      - "KEY=iroha-0"
      - "IROHA_POSTGRES_HOST=iroha-test-postgres"
    volumes:
      - iroha_node0_block_store:/tmp/block_store
      - ./config/node0:/opt/iroha_data
    depends_on:
      - iroha-postgres
    networks:
      - iroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: always

  iroha-node1:
    image: hyperledger/iroha:1.1.1
    container_name: iroha-node1
    expose:
      - 10001
    ports:
      - 50052:50051
    environment:
      - "KEY=iroha-1"
      - "IROHA_POSTGRES_HOST=iroha-test-postgres"
    volumes:
      - iroha_node1_block_store:/tmp/block_store
      - ./config/node1:/opt/iroha_data
    depends_on:
      - iroha-postgres
    networks:
      - iroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: always

  iroha-node2:
    image: hyperledger/iroha:1.1.1
    container_name: iroha-node2
    expose:
      - 10001
    ports:
      - 50053:50051
    environment:
      - "KEY=iroha-2"
      - "IROHA_POSTGRES_HOST=iroha-test-postgres"
    volumes:
      - iroha_node2_block_store:/tmp/block_store
      - ./config/node2:/opt/iroha_data
    depends_on:
      - iroha-postgres
    networks:
      - iroha-net
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    restart: always

  iroha-postgres:
    image: postgres:9.5
    container_name: iroha-test-postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - storage-postgres:/var/lib/postgresql/data
    networks:
      - iroha-net
    restart: always
    command: -c max_prepared_transactions=100


volumes:
  iroha_node0_block_store:
  iroha_node1_block_store:
  iroha_node2_block_store:
  storage-postgres:

networks:
  iroha-net:
    # external:
      name: iroha-net
